[package]
name = "cli-todo-demo-2"
version = "0.1.1"
edition = "2021"
description = "A simple CLI TODO list manager"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
colored = "3.0.0"
